name: Release

on:
  push:
    branches:
      - debug

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install yq via snap
        run: |
          sudo snap install --channel=v3 yq
          yq --version

      - name: Bundle all of the charts
        run: |
          ./bundle.sh

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}"@users.noreply.github.com

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.1
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
